[package]
name = "gtdemo"
version = "0.1.0"
authors = ["Alex Lyon <arcterus@mail.com>"]
edition = "2021"

[dependencies]
redox_syscall = "0.5"
redox-scheme = "0.2.1"
redox-daemon = "0.1.2"
libredox = "0.1.3"
log = "0.4.22"
redox-log = "0.1.4"